# Generated by Django 6.0.1 on 2026-01-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.institute', verbose_name='Институт'),
        ),
    ]
