# Generated by Django 6.0.1 on 2026-02-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textchunk',
            name='embedding',
        ),
    ]
