# Generated by Django 6.0.1 on 2026-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_textchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
