# Generated by Django 6.0.1 on 2026-01-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_textchunk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textchunk',
            old_name='text',
            new_name='content',
        ),
    ]
