# Generated by Django 6.0.1 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_textchunk_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textchunk',
            name='page_number',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='page_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='page_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_question',
            field=models.BooleanField(default=True),
        ),
    ]
