# Generated by Django 6.0.1 on 2026-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_textchunk_page_number_chatmessage_sources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], default='bachelor', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(),
        ),
    ]
