server {
    listen 80;
    server_name rag_project;
    root /var/www/rag_project/static;
    location /static/ {
        alias /var/www/rag_project/static/;
    }

    location / {
        proxy_pass http://django:8000;
    }
}